---
version: "3"

services:
  mysql:
    image: mysql:5.7.24
    environment:
      - MYSQL_DATABASE=rolodex_test
      - MYSQL_ROOT_PASSWORD=system76
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    ports:
      - "3306:3306"
